# This is a YAML configuration file for a data processing pipeline.
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/jugesdebnath7/dataverse/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/summarizer-data.zip
  unzip_dir: artifacts/data_ingestion  